# ######################################################################
# pypiserver docker-compose consistent with docker run command.
# more convenient and usable with coolify
# ######################################################################
version: '3.8'  # Specify a recent docker-compose version

services:
  pypiserver:
    image: pypiserver/pypiserver:latest  # Use the same image
    # volumes:
      # - ~/.htpasswd:/data/.htpasswd  # Mount the htpasswd file
    command: run -P .htpasswd packages  # Set the command to run
